# Generated by Django 5.1.2 on 2024-10-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acesso', '0002_loginlogouthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginLogoutHistory',
        ),
    ]
